### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by AbdelrahmanIbrahem** [AbdelrahmanIbrahem/grad_project#3]
Habiba Adel shouldn't be there 

###expected outcome 
the expected outcome is Abdelrahman 

### Actual outcome 
ana w ent

**Comment by AbdelrahmanIbrahem** [comment]
ha ha ha ha ha ha ha ha ha ha ha ha ha

**Comment by omaramer54** [comment]
UwU

**Comment by omaramer54** [comment]
ara ara

**Comment by AbdelrahmanIbrahem** [comment]
wako wako *__*

**Comment by omaramer54** [comment]
yametei kodasai
